### ISSUE TITLE
Conversion based on LSP not working

### ISSUE THREAD

**Issue by StephanRoemer** [johmsalas/text-case.nvim#20] opened 2022-07-08 23:43 UTC
I'm trying to convert in a lua file with LSP, but when executing these corresponding commands, nothing happens.
However, using the normal convert works (gau, gap, gal, etc...).

Using Neovim 0.7

**Comment by johmsalas** [comment] 2022-07-09 21:33
Hi @StephanRoemer.

It is working for me. also using nvim 0.7

Is the LSP active for the current buffer?
Are you using the default keybindings via the setup() method?
I'm guessing you are invoking them via gaU, gaP, etc...
Is it in normal or visual mode? visual mode does not support LSP

Any other reproduction step is pretty much appreciated

**Comment by StephanRoemer** [comment] 2022-07-10 12:08
Hey @johmsalas!

Thanks for getting back to me :)

Yes, LSP should be active, since nvim-cmp is working. 
Or is there a chance LSP is not working 100% in that case?

Yes, default key bindings (from my plugins.lua):

```
  use { "johmsalas/text-case.nvim",
    config = function()
      require('textcase').setup {}
    end
  }

```
Yep, I'm using gaP, gaU, etc... and I'm in normal mode.
I'm also using which-key and it shows me, that he keybindings are assigned.

When for example executing gaP, nothing happens, e.g. no change in text but also no error message.

**Comment by StephanRoemer** [comment] 2022-07-11 19:20
That's what I get with 2 lua files open:

<img width="543" alt="Bildschirmfoto 2022-07-11 um 21 19 36" src="https://user-images.githubusercontent.com/34496643/178341571-8d96bbae-d394-4fa7-84f6-a543de8483dd.png">

**Comment by johmsalas** [comment] 2022-09-08 14:42
Hi @StephanRoemer!! Sorry for the late answer, I'm just back from vacation.

**Comment by johmsalas** [comment] 2022-09-08 14:57
Just merged a small fix and it works now on my edge case https://github.com/johmsalas/text-case.nvim/pull/27/files

**Comment by StephanRoemer** [comment] 2022-09-08 21:33
> So, there seems to be some kind of miscalculation by `lsp.util.make_position_params()`. Can you check if it presents the same cursor behavior on your case?

Hey man, welcome back! Yes, will test and report back when I’m back t the computer, thanks !

**Comment by StephanRoemer** [comment] 2022-09-09 19:47
Unfortunately, still the same :(

![text case issue](https://user-images.githubusercontent.com/34496643/189431773-0ec93360-33d8-425f-9d09-177c2349be92.gif)

**Comment by johmsalas** [comment] 2022-09-09 21:21
@StephanRoemer 

🤔 .. maybe, is it because the variable is not defined?

https://user-images.githubusercontent.com/6575405/189446842-ce3d9e70-4e20-43ef-9884-738bebf4253b.mov

If you try renaming it using regular LSP rename, does it work?

https://user-images.githubusercontent.com/6575405/189447503-6a27e33a-ae41-4184-8fc1-2fb543c5b07c.mov


btw, do not forget to pull the latest change

**Comment by StephanRoemer** [comment] 2022-09-10 09:36
Yep, did the update via PackerSync.
But you are onto something: I can't even change the variable via LSP rename.
This is on mac, btw. So I think it's an LSP issue and not a text-case issue!

**Comment by johmsalas** [comment] 2022-09-10 12:41
True true. That's why. 

Not even sure how to configure LSP. In my case, I use LunarVim which has all this things working out of the box. I do use Mac and Linux and LSP works. For Lua, LSP rename also works

I appreciate you dedicated some time to answer my questions. I learnt a couple of things and will be able to identify this case faster in the future.

**Comment by StephanRoemer** [comment] 2022-09-11 08:03
Thanks!
I will try to find the root of the problem. Strangely enough, I’m using the same config for Windows and macOS and renaming in Windows works perfectly. 🤷‍♂️

**Comment by johmsalas** [comment] 2022-09-15 14:02
Another thing you can check is if the Language Server supports the rename capability for that specific OS

For this issue, I added some troubleshooting instructions to the readme and can close it now. Hope you can solve your issue

**Closed by johmsalas** 2022-09-15 14:02 UTC
